# Generated by Django 4.1.2 on 2022-11-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliariaSA', '0002_fotos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='TipoImovel',
            new_name='tipoImovel',
        ),
    ]
